:concurrency: 2
:queues:
  - default

:scheduler:
  :dynamic: true
  :schedule:
    due_notification:
      cron: '0 * * * * *'
      class: DueDateNotification
    overdue_notification:
      cron: '0 * * * * *'
      class: OverdueDateNotification
